export const INCREMENT = 'INCREMENT'

export const DECREMENT = 'DECREMENT'

export const ADD_TO_CART = 'ADD_TO_CART'

export const SUBTRACT_FROM_CART = 'SUBTRACT_FROM_CART'

export const DELETE_FROM_CART = 'DELETE_FROM_CART'

export const SHOW_REVIEW_FORM = 'SHOW_REVIEW_FORM'

export const HIDE_REVIEW_FORM = 'HIDE_REVIEW_FORM'

export const SUBMIT_REVIEW_FORM = 'SUBMIT_REVIEW_FORM'

export const ERROR_REVIEW_FORM = 'ERROR_REVIEW_FORM'

export const SUCCESS_REVIEW_FROM = 'SUCCESS_REVIEW_FORM'

export const ADD_NEW_USER = 'ADD_NEW_USER'

export const ADD_NEW_REVIEW = 'ADD_NEW_REVIEW'
